### ISSUE TITLE
fortio improvements

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#2]
Fortio Improvement list:

- [ ] a request id in either headers or query arg or both, way to get cached/non cached request
- [ ] calculate bytes sent/received including headers (to be researched)
- [ ] h2 testing (#452)
- [ ] go over the TODOs
- [ ] warm up time
- [ ] payload option (exists in grpcping)
- [ ] fortio's own perf regression test (ie > 100k qps)

Done:
- [x] curl / single request mode - #21
- [x] ^C support to stop / option to run continuously until ^C - #5 
- [x] struct, json or other structured output for the histogram - #9
- [x] graph (picture) generation - #14
- [x] evaluate/use https://github.com/spf13/cobra -> no - min dependencies
- [x] fixed number of requests mode - #82 
- [x] consider passing a context and/or using channels - #64 

originally from https://github.com/istio/istio/issues/453

**Comment by ymesika** [comment]
@ldemailly `h2` == `HTTP/2` ?

**Comment by ldemailly** [comment]
yes. last time I checked, the default go client/server only did h2 (http 2.0) on tls (https) connections
grpc does exercise h2 though

**Comment by ymesika** [comment]
That’s correct in most implementations and all browsers. I guess TLS is prerequisite to h2 and I noticed it’s still not supported in fortio.

**Comment by ldemailly** [comment]
@ymesika you can use -grpc or -stdclient for tls/h2 today, does it not work for you ?

ps: h2 without tls (h2c) is part of the spec, just that go client isn't supporting it
( https://github.com/golang/go/issues/14141 )

**Comment by ldemailly** [comment]
maybe also calculate https://en.wikipedia.org/wiki/Apdex

**Comment by ldemailly** [comment]
another couple of ideas:
- warm up time, and use the (end of the) warm up to auto set the histogram parameters
- ability to add datasets to the UI / add runs - maybe pop up the form with run parameters and
- label the runs

**Comment by ldemailly** [comment]
> ability to add datasets to the UI / add runs / label the runs

done in #37

**Comment by ldemailly** [comment]
- consider passing a context and/or using channels done in #64 
- fixed number of requests mode done in #82

**Comment by ldemailly** [comment]
getting close to 1.0 - I think after #85, #88, #89, #91, (#92) it'd be enough feature for 1.0 (after some stability baking)

**Comment by ldemailly** [comment]
closing this one 🎉 - filled remaining ideas as seperate new tasks
